reference: "GRCh38.primary_assembly.genome.cleaned.fa"
input_dir: "raw_data"
output_dir: "results"
threads: 4
picard_jar: "picard.jar"
reference_regions: "GRCh38.primary_assembly.genome.cleaned.bed"
annotation: "gencode.v44.basic.annotation.gff3.gz"
windows: "GRCh38.primary_assembly.genome.cleaned.makewindow.bed"
